package com.gymdroid.domain.message;


public enum MessageEnum {
    REGISTER,
    LOGIN,
    ENTER,

    LOGIN_LOAD_DONE_SET,
    LOGIN_LOAD_DONE_TRAINING,
    LOGIN_LOAD_DONE_WORKOUT,
    LOGIN_LOAD_EQUIPMENT,
    LOGIN_LOAD_EQUIPMENT_TYPE,
    LOGIN_LOAD_MUSCLE,
    LOGIN_LOAD_RELATION_WORKOUT_MUSCLE,
    LOGIN_LOAD_TRAINING,
    LOGIN_LOAD_USER_WEIGHT,
    LOGIN_LOAD_WORKOUT,

    ENTER_DONE_SET,
    ENTER_DONE_TRAINING,
    ENTER_DONE_WORKOUT,
    ENTER_EQUIPMENT,
    ENTER_EQUIPMENT_TYPE,
    ENTER_MUSCLE,
    ENTER_MUSCLE_GROUP,
    ENTER_RELATION_WORKOUT_MUSCLE,
    ENTER_TRAINING,
    ENTER_TRAINING_SET,
    ENTER_TRAINING_WORKOUT,
    ENTER_USER_WEIGHT,
    ENTER_WORKOUT,

    OPERATION_ADD_EQUIPMENT,
    OPERATION_DELETE_EQUIPMENT,
    OPERATION_ADD_PRACTICE,
    OPERATION_ADD_MULTIPLE_PRACTICES,
    OPERATION_ADD_USER_WEIGHT,
    OPERATION_DELETE_USER_WEIGHT,
    OPERATION_CREATE_WORKOUT,
    OPERATION_DELETE_WORKOUT,
    OPERATION_CREATE_TRAINING,
    OPERATION_DELETE_TRAINING
}
